release: python manage.py migrate --noinput --verbosity 3
web: gunicorn campus_marketplace.wsgi --log-file - --timeout 120 --workers 1
web: gunicorn campus_marketplace.wsgi --log-file - --timeout 60 --workers 1