# Generated by Django 5.2.8 on 2025-12-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_alter_order_options_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='shipping_method',
            field=models.CharField(blank=True, choices=[('S', 'Standard Shipping'), ('P', 'Pickup')], help_text='Shipping method for this item', max_length=1),
        ),
    ]
