# Generated by Django 5.2.8 on 2025-12-02 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='length',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
