# Generated by Django 5.2.8 on 2025-12-02 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0009_category_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='plural',
            field=models.BooleanField(default=False),
        ),
    ]
