# Generated by Django 5.2.8 on 2025-12-03 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_shippingaddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shippingaddress',
            name='id',
        ),
        migrations.AddField(
            model_name='shippingaddress',
            name='address_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
