# Generated by Django 6.0 on 2025-12-08 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0014_order_external_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='shop_address',
            field=models.TextField(blank=True, help_text='Shop street address'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_alternate_phone',
            field=models.CharField(blank=True, help_text='Shop alternate contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_city',
            field=models.CharField(blank=True, help_text='Shop city', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_country',
            field=models.CharField(default='Philippines', help_text='Shop country', max_length=100),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_logo',
            field=models.ImageField(blank=True, help_text='Shop logo (if seller)', null=True, upload_to='shop_logos/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_phone_number',
            field=models.CharField(blank=True, help_text='Shop contact phone number', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_postal_code',
            field=models.CharField(blank=True, help_text='Shop postal code', max_length=20),
        ),
        migrations.AddField(
            model_name='profile',
            name='shop_province',
            field=models.CharField(blank=True, help_text='Shop province/state', max_length=100),
        ),
    ]
