# Generated by Django 6.0 on 2025-12-08 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_profile_shop_address_profile_shop_alternate_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='seller_identification',
            field=models.ImageField(blank=True, help_text='Identification document', null=True, upload_to='identifications/'),
        ),
    ]
